"use client";

import { useState } from "react";
import { markets, prevalence } from "@/content/prevalence";
import { SHAPES } from "@/content/market-shapes";

/**
 * AMD across the seven major markets, drawn as a cartogram.
 *
 * This started as a choropleth on a world map and was wrong for the data.
 * Seven countries carry figures; the other 169 carry none, so the world map
 * spent most of its frame saying "no data here", and the seven — five of them
 * small European countries — were a few pixels each.
 *
 * Here each country is drawn on its own, scaled so the AREA OF THE SILHOUETTE
 * is proportional to its number of prevalent cases. That is what makes it a
 * cartogram rather than a map: the United States is the biggest shape because
 * it has the most patients, not because it is the largest country. Spain is
 * nearly the size of Germany here, which on a real map it is not, and which is
 * exactly the point. Colour carries the same magnitude on a sequential ramp,
 * so the ordering survives for anyone who reads size poorly.
 *
 * The geometry is generated by scripts/build-market-shapes.mjs, which
 * projects with Equal Earth precisely so the stored areas are comparable
 * between countries.
 */

type Hovered = { name: string; total: string; diagnosed: string; agr: string };

const fmt = (n: number) => `${(n / 1_000_000).toFixed(1)}M`;

const shapeOf = new Map(SHAPES.map((s) => [s.id, s]));
const LOW = Math.min(...markets.map((m) => m.total));
const HIGH = Math.max(...markets.map((m) => m.total));
/** Floor of the colour ramp, so the smallest market still reads as coloured. */
const FLOOR = 0.18;
/**
 * Width of every country's own viewBox, in user units, and how much of it the
 * largest shape fills. The WIDTH is what must be shared: every cell renders at
 * the same pixel width, so one user unit is the same size in all seven and the
 * shapes stay comparable. Height is per country, which is what stops a short,
 * wide country like Germany from reserving a tall empty box.
 */
const CELL = 100;
const FILL = 92;

/**
 * Scale each country so rendered area is proportional to its case count, then
 * normalise the whole set so the largest drawing just fits its cell. Japan is
 * usually what sets the limit: a long archipelago is tall for its area.
 */
const scales = (() => {
  const raw = markets.map((m) => {
    const shape = shapeOf.get(m.id);
    if (!shape) return { id: m.id, s: 0, w: 0, h: 0 };
    const s = Math.sqrt(m.total / shape.area);
    return { id: m.id, s, w: shape.w * s, h: shape.h * s };
  });
  const biggest = Math.max(...raw.map((r) => Math.max(r.w, r.h)));
  const k = FILL / biggest;
  return new Map(raw.map((r) => [r.id, { s: r.s * k, w: r.w * k, h: r.h * k }]));
})();

function fillFor(total: number) {
  const t = FLOOR + (1 - FLOOR) * ((total - LOW) / (HIGH - LOW));
  return `color-mix(in oklab, var(--color-teal-200) ${(t * 100).toFixed(1)}%, var(--color-teal-700))`;
}

export default function PrevalenceMap() {
  const [hovered, setHovered] = useState<Hovered | null>(null);
  const ordered = [...markets].sort((a, b) => b.total - a.total);

  const show = (m: (typeof markets)[number]) =>
    setHovered({ name: m.name, total: fmt(m.total), diagnosed: fmt(m.diagnosed), agr: `${m.agr.toFixed(2)}%` });

  return (
    <div>
      <ul
        className="grid grid-cols-2 items-end gap-x-3 gap-y-4 sm:grid-cols-3 lg:grid-cols-4"
        onPointerLeave={() => setHovered(null)}
      >
        {ordered.map((m) => {
          const shape = shapeOf.get(m.id);
          const size = scales.get(m.id);
          if (!shape || !size) return null;
          return (
            <li key={m.id}>
              <button
                type="button"
                className="wm-cell w-full rounded-lg px-1 py-1 text-left"
                onPointerEnter={() => show(m)}
                onFocus={() => show(m)}
                onBlur={() => setHovered(null)}
                aria-label={`${m.name}: ${fmt(m.total)} living with AMD, ${fmt(m.diagnosed)} diagnosed, growing ${m.agr.toFixed(2)}% a year`}
              >
                <svg
                  viewBox={`0 0 ${CELL} ${size.h.toFixed(1)}`}
                  className="block h-auto w-full"
                  aria-hidden="true"
                >
                  {/* The box is exactly as tall as the shape, and the grid rows
                      are bottom-aligned, so the seven sit on a shared floor
                      with no reserved space above the short ones. */}
                  <g
                    transform={`translate(${(CELL - size.w) / 2} 0) scale(${size.s})`}
                    fill={fillFor(m.total)}
                    stroke="var(--color-ink-950)"
                    strokeWidth={0.8 / size.s}
                    strokeLinejoin="round"
                  >
                    <path d={shape.d} />
                  </g>
                </svg>
                {/* Two lines reserved, so "United Kingdom" wrapping does not push its
                    figure out of line with the row. */}
                <p className="mt-1 min-h-[2.4rem] text-sm font-medium leading-tight text-fog">{m.name}</p>
                <p className="figure text-sm text-fog/75">{fmt(m.total)}</p>
              </button>
            </li>
          );
        })}
      </ul>

      <p className="figure mt-1 text-xs text-fog/70">
        Each country is drawn at a size proportional to the number of people living with AMD, not to its geography.
      </p>

      {/* The readout, pinned rather than floating, so it never needs placing
          and reads the same on hover, keyboard focus and touch. With nothing
          selected it shows the seven-market totals. */}
      <div aria-live="polite" className="mt-5 min-h-[4.5rem] rounded-xl border border-line bg-ink-950/60 px-5 py-4">
        <p className="font-display text-base font-semibold text-fog">{hovered ? hovered.name : "All seven markets"}</p>
        <dl className="mt-2 flex flex-wrap gap-x-8 gap-y-2">
          <div className="flex items-baseline gap-2">
            <dt className="text-sm text-fog/70">Living with AMD</dt>
            <dd className="figure text-base text-fog">{hovered ? hovered.total : fmt(prevalence.totals.total2024)}</dd>
          </div>
          <div className="flex items-baseline gap-2">
            <dt className="text-sm text-fog/70">Diagnosed</dt>
            <dd className="figure text-base text-fog">{hovered ? hovered.diagnosed : fmt(prevalence.totals.diagnosed2024)}</dd>
          </div>
          <div className="flex items-baseline gap-2">
            <dt className="text-sm text-fog/70">Growth a year</dt>
            <dd className="figure text-base text-fog">{hovered ? hovered.agr : `${prevalence.totals.agr.toFixed(2)}%`}</dd>
          </div>
        </dl>
      </div>

      {/* Legend. One sequential ramp, so the gradient is the whole key. */}
      <div className="mt-6">
        <p className="figure text-xs text-fog/70">{prevalence.legend.label}</p>
        <div className="mt-2 flex items-center gap-3">
          <span className="figure text-sm text-fog/85">{prevalence.legend.low}</span>
          <span
            aria-hidden="true"
            className="h-2.5 w-36 rounded-full"
            style={{ background: "linear-gradient(to right in oklab, var(--color-teal-700), var(--color-teal-200))" }}
          />
          <span className="figure text-sm text-fog/85">{prevalence.legend.high}</span>
        </div>
      </div>

      <p className="mt-6 text-sm text-fog/75">{prevalence.global}</p>

      <details className="mt-4 text-sm text-fog/70">
        <summary className="cursor-pointer select-none">The figures behind this chart</summary>
        <div className="mt-3 overflow-x-auto">
          <table className="figure w-full min-w-[30rem] text-left">
            <thead>
              <tr className="text-fog/70">
                <th className="py-1.5 pr-4 font-medium">Market</th>
                <th className="py-1.5 pr-4 text-right font-medium">Living with AMD</th>
                <th className="py-1.5 pr-4 text-right font-medium">Diagnosed</th>
                <th className="py-1.5 text-right font-medium">Growth a year</th>
              </tr>
            </thead>
            <tbody className="text-fog/85">
              {ordered.map((m) => (
                <tr key={m.id} className="border-t border-line">
                  <td className="py-1.5 pr-4">{m.name}</td>
                  <td className="py-1.5 pr-4 text-right">{m.total.toLocaleString("en-GB")}</td>
                  <td className="py-1.5 pr-4 text-right">{m.diagnosed.toLocaleString("en-GB")}</td>
                  <td className="py-1.5 text-right">{m.agr.toFixed(2)}%</td>
                </tr>
              ))}
              <tr className="border-t border-line-strong text-fog">
                <td className="py-1.5 pr-4 font-medium">Seven markets</td>
                <td className="py-1.5 pr-4 text-right font-medium">{prevalence.totals.total2024.toLocaleString("en-GB")}</td>
                <td className="py-1.5 pr-4 text-right font-medium">{prevalence.totals.diagnosed2024.toLocaleString("en-GB")}</td>
                <td className="py-1.5 text-right font-medium">{prevalence.totals.agr.toFixed(2)}%</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-4 max-w-2xl">
          By 2034 the seven-market total is forecast to reach {fmt(prevalence.totals.total2034)} cases, of which{" "}
          {fmt(prevalence.totals.diagnosed2034)} diagnosed.
        </p>
        <ul className="mt-3 flex max-w-2xl flex-col gap-1.5">
          {prevalence.sources.map((s) => (
            <li key={s}>{s}</li>
          ))}
        </ul>
      </details>
    </div>
  );
}
